params:
  epochs: 30
  batch_size: 32
  no_classes: 10
  input_shape: [28, 28]
  loss_functions: sparse_categorical_crossentropy
  metrics: accuracy
  optimizer: SGD
  validation_datasize: 5000

artifacts:
  artifacts_dir: artifacts
  model_dir: model
  model_name: ann
  plots_dir: plots
  chekpoint_dir: checkpoints

logs:
  logs_dir: logs
  general_logs: general_logs
  tensorboard_logs: tensorboard_logs